##############################
#                            #
#    Bungee Auth Reloaded    #
#          Authors           #
#       Old - Vik1395        #
#     Current - Mr_Krab      #
#                            #
#          Support           #
# https://vk.com/id109471660 #
#                            #
##############################



#Do not change this!
"ConfigVersion": 1

#Configuring the Database Connection
DBSetting:
    Host: "127.0.0.1"
    Port: "3306"
    DBName: "Bungee"
    Username: "root"
    Password: "pass"

#Setting up the work of events for unauthorized players
#In future versions there will be more functions
#Free Version
Events:
    Join:
        Cancel: false
        Message: "&4You are not authorized in and can not login to this server"
    BlockBreack: #Premium Version ▼
        Cancel: false
        Message: "&4You can't break blocks until you are authorized"
    BlockPlace: 
        Cancel: false
        Message: "&4You can not place blocks until you are authorized"
    Interact:
        Cancel: false
        Message: "&4You will not be able to interact with this until you are authorized"
    Move:
        Cancel: false
        Message: "&4You can not move until you are authorized"
    Teleport:
        Cancel: false
        Message: "&4You can not teleport until you are authorized"
    InventoryOpen:
        Cancel: false
        Message: "&4You will not be able to interact with this until you are authorized"
    InventoryClick:
        Cancel: false
        Message: "&4You can not change inventory until you are authorized"
    PickupItem:
        Cancel: false
        Message: "&4You can not pick up items until you are authorized"
    DropItem:
        Cancel: false
        Message: "&4You can not drop items until you are authorized"

#Other plugin messages
Messages:
    LoadComplete: "&aPlugin successfully started."
    FistDeveloper: "&eAuthor of the original plugin &4Vik1395."
    CurrentDeveloper: "&eCurrent developer &4Mr_Krab."
    UsingAPI: "&ePlugin uses the &6API Bukkit."
    Thanks: "&eThank you for testing, if you have any questions or problems, please write to https://vk.com/id109471660"
    Reload: "&aPlugin has been reloaded." #Premium Version ◄
    ConfigWarn: "&cAttention!!! The version of your configuration file does not match the current one!"
    ConfigUpdate: "&aYour config has been replaced with the default config. Old config see in the file ConfigOld.txt."