##############################
#                            #
#    Bungee Auth Reloaded    #
#          Authors           #
#       Old - Vik1395        #
#     Current - Mr_Krab      #
#                            #
#          Support           #
# https://vk.com/id109471660 #
#                            #
##############################



#Не изменять это!
"ConfigVersion": 1

#Настройка подключения к базе данных
DBSetting:
    Host: "127.0.0.1"
    Port: "3306"
    DBName: "Bungee"
    Username: "root"
    Password: "pass"

#Настройка работы эвентов для не авторизованных игроков
#В будущих версиях будет больше функций
#Бесплатная версия
Events:
    Join:
        Cancel: false
        Message: "&4Вы не авторизованы и не можете войти на этот сервер"
    BlockBreack: #Премиум версия ▼
        Cancel: false
        Message: "&4Вы не сможете ломать блоки пока не авторизуетесь"
    BlockPlace:
        Cancel: false
        Message: "&4Вы не сможете ставить блоки пока не авторизуетесь"
    Interact:
        Cancel: false
        Message: "&4Вы не сможете взаимодействовать с этим пока не авторизуетесь"
    Move:
        Cancel: false
        Message: "&4Вы не сможете двигаться пока не авторизуетесь"
    Teleport:
        Cancel: false
        Message: "&4Вы не сможете телепортироваться пока не авторизуетесь"
    InventoryOpen:
        Cancel: false
        Message: "&4Вы не сможете взаимодействовать с этим пока не авторизуетесь"
    InventoryClick:
        Cancel: false
        Message: "&4Вы не сможете изменять инвентарь пока не авторизуетесь"
    PickupItem:
        Cancel: false
        Message: "&4Вы не сможете подбирать вещи пока не авторизуетесь"
    DropItem:
        Cancel: false
        Message: "&4Вы не сможете выбрасывать вещи пока не авторизуетесь"

#Прочие сообщения плагина
Messages:
    LoadComplete: "&aПлагин успешно запущен."
    FistDeveloper: "&eАвтор оригинального плагина &4Vik1395."
    CurrentDeveloper: "&eТекущий разработчик &4Mr_Krab."
    UsingAPI: "&eПлагин запущен с использованием &6Bukkit API."
    Thanks: "&eСпасибо за тестирование, если у вас есть вопросы или проблемы сообщите в вк https://vk.com/id109471660"
    Reload: "&aПлагин перезагружен." #Премиум версия ◄
    ConfigWarn: "&cВнимание!!! Версия вашего файла конфигурации не совпадает с текущей!"
    ConfigUpdate: "&aВаш конфиг был заменен на конфиг по умолчанию. Старый конфиг смотрите в файле ConfigOld.txt."