##############################
#                            #
#    Bungee Auth Reloaded    #
#          Authors           #
#       Old - Vik1395        #
#     Current - Mr_Krab      #
#                            #
#          Support           #
# https://vk.com/id109471660 #
#                            #
##############################



# Установите для этого значение значение true, если вы хотите использовать файловую базу данных (SQLite), а не MySQL.
# При включении SQLite нельзя будет выполнять проверки событий на игровых серверах.
Use SQLite: false

# Адрес для подключения к MySQL серверу.
Host: 127.0.0.1

# Порт MySQL сервера.
Port: 3306

# Имя пользователя на MySQL сервере.
Username: root

# Пароль пользователя на MySQL сервере. Если у вас нет пароля, оставьте в этом поле два апострофа (').
Password: 'pass'

# Имя базы данный на MySQL сервере.
DBName: Bungee

# Имя лобби сервера.
Lobby: Lobby

# Вторичный лобби сервер, если первый стал не доступен.
Fallback Lobby: Lobby2

# Сервер авторизации.
AuthLobby: AuthLobby

# Вторичный сервер авторизации, если первый стал не доступен.
Fallback AuthLobby: AuthLobby2

# Установите это значение в true, если вы хотите, чтобы плагин предлагал игрокам регистрировать электронную почту при первом входе на сервер.
Ask Email: false

# Время действия сессии в течении которой вышедший с сервера игрок сможет войти повторно без ввода пароля.
# Если IP адрес игрока изменится, то в целях безопасности ему будет предложенно ввести пароль заного.
Session Length: 5

# Лимит времени в секундах по истечении которого игрока кикнет, если он не авторизовался.
# Установите для этого значение 0, чтобы отключить ограничения времени гостя.
Guest Session Length: 60

# Разрешенные символы для ников. Параметр должен быть в кавычках.
Legal Usernames Characters: "[a-zA-Z0-9_]*"

# Количество игроков, которые могут быть зарегистрированы с одного IP.
Users per IP: 5

# Количество попыток ввода пароля. Если лимит будет исчерпан, то учетная запись временно заблокируется.
Password Tries: 5

# Тайм-аут блокировки (в минутах) для игроков, которые исчерпали лимит попыток ввода пароля.
# Установите для этого значение 0, если хотите отключить эту функцию.
Wrong Password Timeout: 5

# Метод, который запускается каждые 10 секунд и проверяет находится ли игрок на сервере авторизации.
# Если игрок находится на другом сервере, то он будет перенесен на сервер авторизации. 
Guest Server Failsafe Check: true

#---------------------------- ЗОНА PHP API ----------------------------#

# Включение этого приведет к тому, что плагин будет прослушивать запросы API из порта.
Enable PHP API: false

# Порт, на котором плагин будет слушать запросы API.
PHP API Port: 1395

# Пароль, требуемый в запросах API для ответа. Если у вас нет пароля, оставьте в этом поле два апострофа (').
API Password: 'pZe8qNCC6s5NKvYj'

# Установите максимальное количество неправильных попыток ввода пароля api, используемых скриптом php, прежде чем он заблокируется. 
# IP будет заблокирован до удаления из apiblacklist.txt
API Error Limit: 5