# Bungee Auth Reloaded Файл сообщений

# Вы можете настроить сообщения которыйе отправленные Bungee Auth Reloaded здесь. 
# Используйте "%player%" для вывода ника игрока. Имя игрока выводится только в reset_noreg, reset_success, welcome_resume и welcome_register.
# Используйте "%email%" в welcome_register и register если у вас включено требование электронной почты.

illegal_name: "§4Спецсимволы не допустимы!"

register: "Вы еще не зарегистрированы! Введите /reg [пароль] %email%"
reg_success: "Регистрация прошла успешно. Введите /l [пароль] для начала игры."
already_reg: "Вы уже зарегистрировались! Введите /l [пароль]"

nologin_kick: "Вы слишком долго пытались войти в игру!"
login_success: "Вы успешно авторизовались! Теперь вы можете общаться и использовать команды."
already_in: "Вы уже вошли игру!"

logout_success: "Вы успешно вышли из списка авторизованных игроков!"
already_out: "Вы уже вышли из списка авторизованных игроков!"

reset_noreg: "%player% не зарегистрирован на этом сервере."
reset_success: "Пароль %player% успешно сброшен."
no_perm: "У вас нет разрешения на использование этой команды.!"
reg_limit: "Вы достигли максимального количества пользователей, которым разрешено регистрироваться с одного и того же IP-адреса"

force_register: "§6§lУчетная запись %player% была успешно зарегистрирована! \n§e§lВведите /l [пароль] для начала игры."
force_login: "%player% успешно входит в игру!"
force_logout: "Успешно выполнен выход %player%!"
usage_force_logout: "Используйте: /logout force [player]"

pass_change_success: "Пароль был успешно изменен."

wrong_pass: "Введенный вами пароль неверен! Пожалуйста, введите его снова."

welcome_resume: "С возвращением %player%! Ваша сессия была возобновлена."
welcome_login: "С возвращением!, введите /l [пароль]"
welcome_register: "§5§lПриветствуем §e§l%player%§5§l! \n§4§lДля регистрации на сервере введите §2§l/reg [пароль] %email%"
usage_login: "Используйте: /login [пароль] или /l [пароль]"
usage_register: "Используйте: /register [пароль] или /reg [пароль]"
usage_register_email: "Используйте: /register [пароль] [email] или /reg [пароль] [email]"
usage_force_register: "Используйте: /register force [player] [password] или /reg force [player] [password] [email]"
pre_login: "Вы не сможете использовать команды и писать в чат пока не авторизуетесь."

error_authlobby: "Ошибка! Не удается подключиться к серверу авторизации."
error_lobby: "Ошибка! Не удается подключиться к игровому серверу."

spammed_password: "Ваш чат временно заблокирован, так как вы ввели неверный пароль слишком много раз"
resetp: "Вы были кикнуты с сервера!"